backup_data/urls.py
from django.urls import path

from .views import BackupHomepageView, download_data_view


app_name = 'backup'

urlpatterns = [
    path('homepage/', BackupHomepageView.as_view(), name='homepage'),
    path('download/<slug:slug>/', download_data_view, name='download')
]

chat/urls.py
from django.urls import path

from .views import index, room

app_name = 'chat'

urlpatterns = [
    path('', index, name='index'),
    path('<str:room_name>/', room, name='room'),

]

finace_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from rest_framework import routers, serializers, viewsets
from rest_framework_simplejwt import views as jwt_views

from frontend.api.views import homepage_api_view


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('frontend.urls')),
    path('portfolio/', include('tickers.urls')),
    path('accounts/', include('accounts.urls')),
    path('settings/', include('settings.urls')),
    path('chat/', include('chat.urls')),
    path('backup/', include('backup_data.urls')),


    # api
    path('api/', homepage_api_view, name='api_homepage'),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('api/tickers/', include('tickers.api.urls')),
    path('api/accounts/', include('accounts.api.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# 22

backup_data/models.py
from django.db import models

# Create your models here.


class BackupSignature(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title

backup_data/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator

from tickers.models import Ticker, User, Portfolio, UserTicker
from .models import BackupSignature
from .admin import UserResources, TickerResources, PortfolioResources, UserTickerResources

from .models import BackupSignature


@method_decorator(staff_member_required, name='dispatch')
class BackupHomepageView(TemplateView):
    template_name = 'backupFolder/backupDatabase.html'

    def get_context_data(self, **kwargs):
        context = super(BackupHomepageView, self).get_context_data(**kwargs)
        # Ticker
        context['count_ticker'] = Ticker.objects.count()
        context['last_ticker'] = BackupSignature.objects.filter(title='ticker').last().timestamp if BackupSignature.objects.filter(title='ticker').exists() else 'No backup'
        # User
        context['count_user'] = User.objects.count()
        context['last_user'] = BackupSignature.objects.filter(title='ticker').last().timestamp if BackupSignature.objects.filter(title='user').exists() else 'No backup'
        # portfolio
        context['count_portfolio'] = Portfolio.objects.count()
        context['last_portfolio'] = BackupSignature.objects.filter(title='ticker').last().timestamp if BackupSignature.objects.filter(title='portfolio').exists() else 'No backup'
        # UserTicker
        context['count_user_ticker'] = UserTicker.objects.count()
        context['last_user_ticker'] = BackupSignature.objects.filter(title='ticker').last().timestamp if BackupSignature.objects.filter(title='user_ticker').exists() else 'No backup'
        return context


@staff_member_required
def download_data_view(request, slug):
    print('hittes!')
    key_list = ['user', 'portfolio', 'user_ticker', 'ticker']
    resources = {
        'user': UserResources,
        'portfolio': PortfolioResources,
        'user_ticker': UserTickerResources,
        'ticker': TickerResources
    }
    key_exists = True if slug in key_list else False
    if not key_exists:
        print('not here')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    resource = resources[slug]
    dataset = resource().export()
    response = HttpResponse(dataset.csv, content_type='text/csv')
    response['Content-Disposition'] = f'attachment; filename="{slug}.csv"'
    BackupSignature.objects.create(title=slug)
    return response

backup_data/templates/backupFolder/backupDatabase.html
{% extends 'dashboard.html' %}

{% block content %}
 <!-- Header -->
    <div class="header bg-primary pb-6">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0">Tickers</h6>
              <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                  <li class="breadcrumb-item"><a href="{% url 'homepage' %}"><i class="fas fa-home"></i></a></li>
                  <li class="breadcrumb-item active" aria-current="page">BackUp Page</li>
                </ol>
              </nav>
            </div>
            <div class="col-lg-6 col-5 text-right">




            </div>
          </div>

        </div>
      </div>
    </div>
    <!-- Page content -->
     <div class="container-fluid mt--6">
         <div class="row">
             <div class="col-12">
                 <div class="card">
            <!-- Card header -->
                     <div class="card-header border-0">
                         <h3 class="mb-0">All Data</h3>
                         <br />
                         <hr />
                         
                         <hr />
                     </div>
                     <!-- Light table -->

                     <!-- Card footer -->

                 </div>
             </div>
             <div class="col-4">
                 <div class="card">
                     <!-- Card header -->
                     <div class="card-header border-0">
                         <h3 class="mb-0">Tickers</h3>
                     </div>
                     <!-- Light table -->
                     <div class="table-responsive">
                         <table class="table align-items-center table-flush">
                             <thead class="thead-light">
                                 <tr>
                                     <th scope="col" class="sort" data-sort="name">Count</th>
                                     <th scope="col" class="sort" data-sort="name">Last Download</th>
                                 </tr>
                             </thead>
                             <tbody class="list">
                                 <tr>
                                     <td class="budget">{{ count_ticker }}</td>
                                     <td class="budget">{{ last_ticker }}</td>

                                 </tr>
                             </tbody>
                         </table>
                     </div>
                     <!-- Card footer -->
                     <div class="card-footer py-4">
                         <a href="{% url 'backup:download' 'ticker' %}" style="display: inline" type="button" class="btn btn-success" >
                             Create Backup
                         </a>
                     </div>
                 </div>
             </div>
             <div class="col-4">
                 <div class="card">
                     <!-- Card header -->
                     <div class="card-header border-0">
                         <h3 class="mb-0">User</h3>
                     </div>
                     <!-- Light table -->
                     <div class="table-responsive">
                         <table class="table align-items-center table-flush">
                             <thead class="thead-light">
                                 <tr>
                                     <th scope="col" class="sort" data-sort="name">Count</th>
                                     <th scope="col" class="sort" data-sort="name">Last Download</th>
                                 </tr>
                             </thead>
                             <tbody class="list">
                                 <tr>
                                     <td class="budget">{{ count_user }}</td>
                                     <td class="budget">{{ last_user }}</td>

                                 </tr>
                             </tbody>
                         </table>
                     </div>
                     <!-- Card footer -->
                     <div class="card-footer py-4">
                         <a href="{% url 'backup:download' 'user' %}" style="display: inline" type="button" class="btn btn-success" >
                             Create Backup
                         </a>
                     </div>
                 </div>
             </div>
             <div class="col-4">
                 <div class="card">
                     <!-- Card header -->
                     <div class="card-header border-0">
                         <h3 class="mb-0">Portfolio</h3>
                     </div>
                     <!-- Light table -->
                     <div class="table-responsive">
                         <table class="table align-items-center table-flush">
                             <thead class="thead-light">
                                 <tr>
                                     <th scope="col" class="sort" data-sort="name">Count</th>
                                     <th scope="col" class="sort" data-sort="name">Last Download</th>
                                 </tr>
                             </thead>
                             <tbody class="list">
                                 <tr>
                                     <td class="budget">{{ count_portfolio }}</td>
                                     <td class="budget">{{ last_portfolio }}</td>

                                 </tr>
                             </tbody>
                         </table>
                     </div>
                     <!-- Card footer -->
                     <div class="card-footer py-4">
                         <a href="{% url 'backup:download' 'portfolio' %}" style="display: inline" type="button" class="btn btn-success" >
                             Create Backup
                         </a>
                     </div>
                 </div>
             </div>
             <div class="col-4">
                 <div class="card">
                     <!-- Card header -->
                     <div class="card-header border-0">
                         <h3 class="mb-0">User Tickers</h3>
                     </div>
                     <!-- Light table -->
                     <div class="table-responsive">
                         <table class="table align-items-center table-flush">
                             <thead class="thead-light">
                                 <tr>
                                     <th scope="col" class="sort" data-sort="name">Count</th>
                                     <th scope="col" class="sort" data-sort="name">Last Download</th>
                                 </tr>
                             </thead>
                             <tbody class="list">
                                 <tr>
                                     <td class="budget">{{ count_user_ticker }}</td>
                                     <td class="budget">{{ last_user_ticker }}</td>

                                 </tr>
                             </tbody>
                         </table>
                     </div>
                     <!-- Card footer -->
                     <div class="card-footer py-4">
                         <a href="{% url 'backup:download' 'user_ticker' %}" style="display: inline" type="button" class="btn btn-success" >
                             Create Backup
                         </a>
                     </div>
                 </div>
             </div>
             <div class="col-4">
                 <div class="card">
                     <!-- Card header -->
                     <div class="card-header border-0">
                         <h3 class="mb-0">Group</h3>
                     </div>
                     <!-- Light table -->
                     <div class="table-responsive">
                         <table class="table align-items-center table-flush">
                             <thead class="thead-light">
                                 <tr>
                                     <th scope="col" class="sort" data-sort="name">Count</th>
                                     <th scope="col" class="sort" data-sort="name">Last Download</th>
                                 </tr>
                             </thead>
                             <tbody class="list">
                                 <tr>
                                     <td class="budget">{{ count_group }}</td>
                                     <td class="budget">{{ last_group }}</td>

                                 </tr>
                             </tbody>
                         </table>
                     </div>
                     <!-- Card footer -->
                     <div class="card-footer py-4">
                         <a href="{% url 'backup:download' 'group' %}" style="display: inline" type="button" class="btn btn-success" >
                             Create Backup
                         </a>
                     </div>
                 </div>
             </div>
      <!-- Dark table -->


    </div>

{% endblock %}