chat/urls.py
from django.urls import path

from .views import index, room

app_name = 'chat'

urlpatterns = [
    path('', index, name='index'),
    path('<str:room_name>/', room, name='room'),

]

finace_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from rest_framework import routers, serializers, viewsets
from rest_framework_simplejwt import views as jwt_views

from frontend.api.views import homepage_api_view


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('frontend.urls')),
    path('portfolio/', include('tickers.urls')),
    path('accounts/', include('accounts.urls')),
    path('settings/', include('settings.urls')),
    path('chat/', include('chat.urls')),
    path('backup/', include('backup_data.urls')),


    # api
    path('api/', homepage_api_view, name='api_homepage'),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('api/tickers/', include('tickers.api.urls')),
    path('api/accounts/', include('accounts.api.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# 22

tickers/api/urls.py
from django.urls import path

from .views import (ticker_homepage_api_view,
                    TickerListApiView, TickerUpdateApiView,
                    PortfolioListApiView, PortfolioRetrieveUpdateDeleteApiView,
                    TickerAnalysisApiView,
                    UserTickerListApiView, UserTickerDetailApiView,
                    GroupListApiView, portfolio_total_data_view, UserTickerUpdateFromYahooApiView,
                    portfolio_refresh_data_view
                    )

app_name = 'api_tickers'

urlpatterns = [
    path('', ticker_homepage_api_view, name='home'),
    path('ticker/list/', TickerListApiView.as_view(), name='ticker_list'),
    path('ticker/update/<int:pk>/', TickerUpdateApiView.as_view(), name='ticker_update'),
    path('portfolio/list/', PortfolioListApiView.as_view(), name='portfolio_list'),
    path('portfolio/update-delete/<int:pk>/', PortfolioRetrieveUpdateDeleteApiView.as_view(), name='portfolio_update_delete'),
    path('portfolio/ticker/analysis/<int:pk>/', TickerAnalysisApiView.as_view(), name='ticker_analysis'),
    path('portfolio/user-ticker/', UserTickerListApiView.as_view(), name='user_ticker_list_view'),
    path('portfolio/user-ticker/detail/<int:pk>/', UserTickerDetailApiView.as_view(), name='user_ticker_detail_view'),
    path('group/list-create/', GroupListApiView.as_view(), name='group_list'),
    path('portfolio-total-data-by-user/', portfolio_total_data_view, name='portfolio_total_data_by_user'),
    path('user-ticker/update-from-api/<int:pk>/', UserTickerUpdateFromYahooApiView.as_view(), name='user_ticker_update_from_yahoo'),
    path('portfolio-refresh-data/<int:pk>/', portfolio_refresh_data_view, name='port_refresh_data'),

]

tickers/urls.py
from django.urls import path

from .views import (portofolio_view, TickerListView, TickerUpdateView, ticker_delete_view,
                    PortfoliosListView)

from .validate_views import validate_create_ticker_form, validate_create_group_form, validate_portfolio_create_form
from .actions import (refresh_ticker_data, refresh_portfolio_action_view, validate_ticker_create_from_portfolio_view,
                      refresh_tickers_data, buy_tickers_from_effective_frontier_view, update_ticker_api_view,
                      delete_ticker_from_portfolio_view, update_user_ticker_view, delete_portfolio_view,
                      add_random_tickers_to_portfolio
                      )
from .ajax_views import (ajax_add_ticker_modal, ajax_portfolio_effective_frontier_view, ajax_show_historic_graph,
                         search_tickers, create_random_portfolios_view, ajax_ticker_modal,ajax_refresh_portfolio_data
                         )

app_name = 'portfolio'

urlpatterns = [
    path('<int:id>/', portofolio_view, name='portofolio_detail'),

    path('tickers/', TickerListView.as_view(), name='ticker_list_view'),
    path('tickers/update/<int:pk>/', TickerUpdateView.as_view(), name='ticker_update'),
    path('tickers/delete/<int:id>/', ticker_delete_view, name='ticker_delete_view'),

    path('portfolios-list-view/', PortfoliosListView.as_view(), name='portfolio_list_view'),
    path('portfolio/delete/<int:pk>/', delete_portfolio_view, name='delete_portfolio'),

    path('validate/create-ticker/', validate_create_ticker_form, name='validate_create_ticker'),
    path('validate/create-group/', validate_create_group_form, name='validate_create_group'),
    path('validate/create-portfolio/', validate_portfolio_create_form, name='validate_create_portfolio'),

    path('validate/create-ticker-from-portfolio/<int:pk>/<int:dk>/', validate_ticker_create_from_portfolio_view,
         name='validate_create_ticker_from_portfolio'),

    path('add-tickers-to-portfolio-frontier/<int:pk>/', buy_tickers_from_effective_frontier_view,
         name='buy_tickers_effective_frontier'),

    path('update-ticker-action/<int:pk>/<slug:slug>/', update_ticker_api_view, name='update_ticker_api_view'),
    path('delete-ticker-from-portfolio/<int:pk>/', delete_ticker_from_portfolio_view,
         name='delete_ticker_from_portfolio'),

    path('update-ticker-from-portfolio/<int:pk>/', update_user_ticker_view, name='update_user_ticker'),

    path('refresh-ticker-data/<int:pk>/', refresh_ticker_data, name='refresh_ticker_data'),
    path('refresh-tickers-data/', refresh_tickers_data, name='refresh_tickers_data'),
    path('refresh-portfolio-tickers/<int:pk>/', refresh_portfolio_action_view, name='refresh_portfolio_tickers'),

    path('ajax/create-ticker-modal/<int:pk>/<int:dk>/', ajax_add_ticker_modal, name='ajax_add_ticker_modal'),
    path('ajax/portfolio/effective-frontier/<int:pk>/', ajax_portfolio_effective_frontier_view, name='ajax_effective_frontier'),
    path('ajax/show-graph/<int:pk>/', ajax_show_historic_graph, name='ajax_show_graph'),
    path('ajax/search-tickers/<int:pk>/', search_tickers, name='ajax-search_tickers'),
    path('create-random-portfolio-tickers/<int:pk>/', create_random_portfolios_view, name='create_random_port_tickers'),

    path('add-random-tickers-to-portfolio/<int:pk>/', add_random_tickers_to_portfolio, name='add_random_tickers_to_portfolio'),
    path('ajax-show-ticker-modal/<int:pk>/<int:dk>/', ajax_ticker_modal, name='ajax_show_ticker_modal'),
    path('ajax/update-ticker-data/<int:pk>/', ajax_refresh_portfolio_data, name='ajax_refresh_portfolio_ticker_data'),


  
    # strategies



]

tickers/api/views.py
from rest_framework.decorators import api_view
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework import generics
from rest_framework import filters
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework.viewsets import ModelViewSet
from django.shortcuts import get_object_or_404

from django_filters.rest_framework import DjangoFilterBackend
from .helpers import calculate_sum, calculate_avg

from .serializers import (TickerSerializer, PortfolioSerializer,
                          UserTickerSerializer, TickerAnalysisSerializer,
                          GroupSerializer, UserTickerUpdateFromApiSerializer
                          )
from ..models import Ticker, Portfolio, UserTicker, Group
from .permisions import IsPublicOrCreatorPermission, IsOwnerOrReadOnly, UserTickerReadIfPublicOrCreatePermission


@api_view(['GET'])
def ticker_homepage_api_view(request, format=None):
    return Response({
        'tickers': reverse('api_tickers:ticker_list', request=request, format=format),
        'portfolios': reverse('api_tickers:portfolio_list', request=request, format=format),
        'user_tickers': reverse('api_tickers:user_ticker_list_view', request=request, format=format),
        'group': reverse('api_tickers:group_list', request=request, format=format),
        'total_data_by_user': reverse('api_tickers:portfolio_total_data_by_user', request=request, format=format)
    })


class GroupListApiView(generics.ListCreateAPIView):
    queryset = Group.objects.all()
    serializer_class = GroupSerializer
    permission_classes = [AllowAny, ]


class TickerListApiView(generics.ListCreateAPIView):
    queryset = Ticker.objects.all()
    serializer_class = TickerSerializer
    permission_classes = [AllowAny, ]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter]
    filterset_fields = ['group']
    search_fields = ['title', 'ticker']



class TickerUpdateApiView(generics.RetrieveUpdateAPIView):
    queryset = Ticker.objects.all()
    serializer_class = TickerSerializer
    permission_classes = [AllowAny, ]


class TickerAnalysisApiView(generics.RetrieveAPIView):
    queryset = Ticker.objects.all()
    serializer_class = TickerAnalysisSerializer


class PortfolioListApiView(generics.ListCreateAPIView):
    # queryset = Portfolio.objects.all()
    serializer_class = PortfolioSerializer
    permission_classes = [IsPublicOrCreatorPermission, ]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter]
    filterset_fields = ['user', 'is_public']
    search_filters = ['title', ]

    def get_queryset(self):
        user = self.request.user
        user_qs = Portfolio.objects.filter(user=user) if user.is_authenticated else Portfolio.objects.none()
        public_qs = Portfolio.objects.filter(is_public=True)
        qs = user_qs|public_qs
        qs = Portfolio.filter_data(self.request, qs)

        return qs

    def filter_queryset(self, queryset):
        filter_backends = self.filter_backends

        # for backend in list(filter_backends):
        #  queryset = backend().filter_queryset(self.request, queryset, view=self)
        return queryset


class PortfolioRetrieveUpdateDeleteApiView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Portfolio.objects.all()
    serializer_class = PortfolioSerializer
    permission_classes = [IsPublicOrCreatorPermission, ]


class UserTickerUpdateFromYahooApiView(generics.RetrieveUpdateAPIView):
    queryset = UserTicker.objects.all()
    serializer_class = UserTickerUpdateFromApiSerializer
    


class UserTickerListApiView(generics.ListCreateAPIView):
    queryset = UserTicker.objects.all()
    serializer_class = UserTickerSerializer
    permission_classes = [IsOwnerOrReadOnly, ]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter]
    filterset_fields = ['portfolio', 'is_buy']
    search_filters = ['ticker', 'portfolio']


class UserTickerDetailApiView(generics.RetrieveUpdateDestroyAPIView):
    queryset = UserTicker.objects.all()
    serializer_class = UserTickerSerializer
    permission_classes = [UserTickerReadIfPublicOrCreatePermission, ]


@api_view(['GET'])
def portfolio_total_data_view(request, format=None):
    user = request.user
    print('user', user)
    qs = Portfolio.objects.filter(user=user)
    active_qs = qs.filter(is_locked=False)
    total_money_investment = calculate_sum('starting_investment', qs)
    current_value = calculate_sum('current_value', qs)
    expected_portofolio_return = calculate_avg('expected_portfolio_return', qs)
    volatility = calculate_avg('expected_portfolio_volatility', qs)
    return Response({
        'starting_investment': total_money_investment,
        'current_value': current_value,
        'volatility': volatility,
        'return': expected_portofolio_return
    })


@api_view(['GET', ])
def portfolio_refresh_data_view(request, pk,format=None):
    instance = get_object_or_404(Portfolio, id=pk)
    if not request.user == instance.user:
        return Response({
            'message': 'You dont own this portfolio!'
        })
    for tick in instance.tickers.all():
        tick.update_basic_data()
    instance.save()
    instance.refresh_from_db()
    return Response({
        'message': 'Update with Success'
    })

tickers/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, CreateView, UpdateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy, reverse
from django.contrib import messages

from .models import Portfolio, Ticker, Group
from .form import UserTickerForm, TickerForm, GroupForm, PortFolioForm


from .get_stock_data import read_data, check_if_file_exists
import pandas as pd
from scipy.stats import norm


def portofolio_view(request, id):
    context = dict()
    instance = get_object_or_404(Portfolio, id=id)
    instance.calculate_returns_and_volatility()
    portForm = PortFolioForm(request.POST or None, instance=instance)
    if portForm.is_valid():
        portForm.save()
        return redirect(instance.get_absolute_url())
    context['instance'] = instance
    create_form = UserTickerForm(request.POST or None, initial={'portfolio': instance})
    context['create_form'] = create_form
    context['ticker_form'] = TickerForm()
    context['portForm'] = portForm
    if create_form.is_valid():
        create_form.save()
        return redirect(instance.get_absolute_url())
    ids = []
    forecast_data = []
    for tic in instance.tickers.all():
        ids.append(tic.ticker.id)
        forecast_data.append([tic, tic.ticker.forecast()])
    context['forecast_data'] = forecast_data
    context['tickers'] = Ticker.objects.all()[:100]
    return render(request, 'portfolio.html', context)


class TickerListView(ListView):
    model = Ticker
    paginate_by = 20
    template_name = 'ticker_list_view.html'
    queryset = Ticker.objects.all()

    def get_queryset(self):
        return Ticker.filter_data(self.request)

    def get_context_data(self, **kwargs):
        context = super(TickerListView, self).get_context_data(**kwargs)
        context['groups'] = Group.objects.all()
        context['ticker_form'] = TickerForm()
        context['group_form'] = GroupForm()

        return context


@method_decorator(login_required, name='dispatch')
class TickerUpdateView(UpdateView):
    template_name = 'tickers/update_view.html'
    model = Ticker
    form_class = TickerForm
    success_url = reverse_lazy('portfolio:ticker_list_view')
    queryset = Ticker.objects.all()

    def get_context_data(self, **kwargs):
        context = super(TickerUpdateView, self).get_context_data(**kwargs)
        file_exists = check_if_file_exists(self.object.ticker)

        if file_exists:
            print('file exists')
            context['macd'], context['safe_line'], context['tick'] = self.object.calculate_macd()
            df_sma = self.object.bb()
            df_sma.dropna(inplace=True)
            df_sma = [df_sma.columns.tolist()] + df_sma.reset_index().values.tolist()

            df = self.object.create_data_for_chart()
            df = [df.columns.tolist()] + df.reset_index().values.tolist()
            new_list, new_sma_list = [], []
            for ele in df:
                if self.object.ticker in ele:
                    continue
                else:
                    new_list.append(ele)
            for ele in df_sma:
                new_sma_list.append(ele) if self.object.ticker in ele else ''

            context['df_sma'] = df_sma
            context['chart_data'] = new_list
            context['delete_url'] = self.object.get_delete_url()
            context['graph'] = self.object.monte_carlo_simulation()
            context['ticker_avg'] = self.object.calculate_averages()
            context['drop_5_prop'] = self.object.calculate_probability_of_drop(0.05)
            context['gain_5_prop'] = self.object.calculate_probability_of_drop(-0.05)

        else:
            messages.warning(self.request, f'Code {self.object.ticker} dont exist on yahoo database')

        return context

    def form_valid(self, form):
        form.save()
        return super(TickerUpdateView, self).form_valid(form)


@login_required
def ticker_delete_view(request, id):
    ticker = get_object_or_404(Ticker, id=id, user=request.user)
    ticker.delete()
    return redirect('portfolio:ticker_list_view')


@method_decorator(login_required, name='dispatch')
class PortfoliosListView(ListView):
    template_name = 'portfolios_list_view.html'
    model = Portfolio
    paginate_by = 50

    def get_queryset(self):
        user = self.request.user
        return Portfolio.objects.filter(user=user)

    def get_context_data(self, **kwargs):
        context = super(PortfoliosListView, self).get_context_data(**kwargs)
        context['form'] = PortFolioForm(self.request.POST or None, initial={'user': self.request.user})

        return context


@login_required
def portfolio_delete_view(request, pk):
    obj = get_object_or_404(Portfolio, id=pk, user=request.user)
    obj.delete()
    return redirect(reverse('homepage'))


def calculate_relative_strength_index_view(request):
    tickers = Ticker.objects.all()[:10]
    for ticker in tickers:
        df = read_data(ticker.ticker)

tickers/templates/ticker_list_view.html
{% extends 'dashboard.html' %}

{% block content %}

 <!-- Header -->
    <div class="header bg-primary pb-6">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0">Tickers</h6>
              <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                  <li class="breadcrumb-item"><a href="{% url 'homepage' %}"><i class="fas fa-home"></i></a></li>
                  <li class="breadcrumb-item active" aria-current="page">Tickers</li>
                </ol>
              </nav>
            </div>
            <div class="col-lg-6 col-5 text-right">
                <a href="{% url 'portfolio:refresh_tickers_data' %}" class="btn btn-warning" >
                    Refresh Data
                </a>
                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModal">
                    New Ticker
                </button>

                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Ticker</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <h4>Create New Ticker</h4>
                                <form method="post" class="form" action="{% url 'portfolio:validate_create_ticker' %}">
                                    {% csrf_token %}
                                    {{ ticker_form }}
                                    <button class="btn btn-success" type="submit"><i class="fa fa-save"></i> Save </button>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
          </div>

        </div>
      </div>
    </div>
    <!-- Page content -->
     <div class="container-fluid mt--6">
         <div class="row">
             <div class="col-12">
                 <div class="card">
            <!-- Card header -->
                     <div class="card-header border-0">
                         <h3 class="mb-0">Tickers</h3>
                     </div>
                     <!-- Light table -->
                     <table class="table table-bordered">
                              <thead class="thead-light">
                                  <tr>
                                      <th scope="col">Ticker</th>
                                      <th scope="col">Rate of Return</th>
                                      <th scope="col">Security</th>
                                      <th scope="col">Value</th>
                                      <th scope="col">Sharp</th>
                                      <th scope="col">Beta</th>
                                      <th scope="col">Market Variance</th>
                                      <th scope="col">Coverage</th>
                                      <th scope="col">Camp</th>
                                      <th scope="col">Last Update</th>

                                  </tr>
                              </thead>
                              <tbody>
                              {% for ticker in object_list %}
                                  <tr>
                                      <th><a href="{{ ticker.get_absolute_url }}" >{{ ticker }}</a></th>
                                      <td>{{ ticker.simply_return }} % </td>
                                      <td>{{ ticker.standard_deviation }} % </td>
                                      <td>{{ ticker.price }} </td>
                                      <td>{{ ticker.sharp }}</td>
                                      <td>{{ ticker.beta }}</td>
                                      <td>{{ ticker.market_variance }}</td>
                                      <td>{{ ticker.coverage }}</td>
                                      <td>{{ ticker.camp }}</td>
                                      <td>{{ ticker.updated|timesince }}</td>
                                  </tr>
                              {% endfor %}
                              </tbody>
                          </table>
                     <!-- Card footer -->

                 </div>
             </div>
             <div class="col-4">
                 <div class="card">
            <!-- Card header -->
                     <div class="card-header border-0">
                         <h3 class="mb-0">Groups</h3>


                <!-- Modal -->
                <div class="modal fade" id="exampleModalgroup" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Group</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <h4>Create New Group</h4>
                                <form method="post" class="form" action="{% url 'portfolio:validate_create_group' %}">
                                    {% csrf_token %}
                                    {{ group_form }}
                                    <button class="btn btn-success" type="submit"><i class="fa fa-save"></i> Save </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                     </div>
                     <!-- Light table -->
                     <div class="table-responsive">
                         <table class="table align-items-center table-flush">
                             <thead class="thead-light">
                             <tr>
                                 <th scope="col" class="sort" data-sort="name">Group</th>
                                 <th scope="col" class="sort" data-sort="name">Code</th>

                                 <th scope="col"></th>
                             </tr>
                             </thead>
                             <tbody class="list">
                             {% for group in groups %}
                             <tr>
                                 <td class="budget">{{ group.title }}</td>
                                 <td class="budget">{{ group.code }}</td>
                                 <td class="text-right">
                                     <div class="dropdown">
                                         <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                             <i class="fas fa-ellipsis-v"></i>
                                         </a>
                                         <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                             <a class="dropdown-item" href="#">Edit</a>
                                             <a class="dropdown-item" href="#">Delete</a>
                                         </div>
                                     </div>
                                 </td>
                             </tr>
                             {% endfor %}
                             </tbody>
                         </table>

            </div>
            <!-- Card footer -->
            <div class="card-footer py-4">
              <button style="display: inline" type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModalgroup">
                    New Group
                </button>
            </div>
          </div>
        </div>
      </div>
      <!-- Dark table -->


    </div>
{% endblock %}