chat/urls.py
from django.urls import path

from .views import index, room

app_name = 'chat'

urlpatterns = [
    path('', index, name='index'),
    path('<str:room_name>/', room, name='room'),

]

finace_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from rest_framework import routers, serializers, viewsets
from rest_framework_simplejwt import views as jwt_views

from frontend.api.views import homepage_api_view


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('frontend.urls')),
    path('portfolio/', include('tickers.urls')),
    path('accounts/', include('accounts.urls')),
    path('settings/', include('settings.urls')),
    path('chat/', include('chat.urls')),
    path('backup/', include('backup_data.urls')),


    # api
    path('api/', homepage_api_view, name='api_homepage'),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('api/tickers/', include('tickers.api.urls')),
    path('api/accounts/', include('accounts.api.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# 22

frontend/urls.py
from django.urls import path

from .views import (homepage, login_view, StrategyView, moving_average_trading_strategy_view,
                    add_ticker_to_strategy_view, delete_ticker_from_strategy_view,

                    )

from .ajax_views import ajax_show_portfolios_view
from .action_views import add_portfolio_to_strategy_view


urlpatterns = [
    path('', homepage, name='homepage'),
    path('login/', login_view, name='login'),

    # strategies
    path('strategies/', StrategyView.as_view(), name='strategy_homepage'),
    path('strategies/moving-average-trading-strategy/', moving_average_trading_strategy_view, name='moving_average_trading'),
    path('strategies/add-to-strategy-ticker/<int:pk>/<int:dk>/', add_ticker_to_strategy_view, name='add_to_strategy_ticker'),
    path('strategies/delete-ticker-from-strategy/<int:pk>/', delete_ticker_from_strategy_view, name='remove_ticker_from_strategy'),

    # action views
    path('strategies/add-port-to-strategy/<int:pk>/<int:dk>/', add_portfolio_to_strategy_view, name='add_portfolio_to_strategy'),

    # ajax views
    path('strategies/ajax/show-portfolio/<int:pk>/', ajax_show_portfolios_view, name='ajax_portfolios_modal')
]

settings/urls.py
from django.urls import path


from .views import homepage_view

app_name = 'setting'

urlpatterns = [
    path('', homepage_view, name='homepage'),
]

tickers/urls.py
from django.urls import path

from .views import (portofolio_view, TickerListView, TickerUpdateView, ticker_delete_view,
                    PortfoliosListView)

from .validate_views import validate_create_ticker_form, validate_create_group_form, validate_portfolio_create_form
from .actions import (refresh_ticker_data, refresh_portfolio_action_view, validate_ticker_create_from_portfolio_view,
                      refresh_tickers_data, buy_tickers_from_effective_frontier_view, update_ticker_api_view,
                      delete_ticker_from_portfolio_view, update_user_ticker_view, delete_portfolio_view,
                      add_random_tickers_to_portfolio
                      )
from .ajax_views import (ajax_add_ticker_modal, ajax_portfolio_effective_frontier_view, ajax_show_historic_graph,
                         search_tickers, create_random_portfolios_view, ajax_ticker_modal,ajax_refresh_portfolio_data
                         )

app_name = 'portfolio'

urlpatterns = [
    path('<int:id>/', portofolio_view, name='portofolio_detail'),

    path('tickers/', TickerListView.as_view(), name='ticker_list_view'),
    path('tickers/update/<int:pk>/', TickerUpdateView.as_view(), name='ticker_update'),
    path('tickers/delete/<int:id>/', ticker_delete_view, name='ticker_delete_view'),

    path('portfolios-list-view/', PortfoliosListView.as_view(), name='portfolio_list_view'),
    path('portfolio/delete/<int:pk>/', delete_portfolio_view, name='delete_portfolio'),

    path('validate/create-ticker/', validate_create_ticker_form, name='validate_create_ticker'),
    path('validate/create-group/', validate_create_group_form, name='validate_create_group'),
    path('validate/create-portfolio/', validate_portfolio_create_form, name='validate_create_portfolio'),

    path('validate/create-ticker-from-portfolio/<int:pk>/<int:dk>/', validate_ticker_create_from_portfolio_view,
         name='validate_create_ticker_from_portfolio'),

    path('add-tickers-to-portfolio-frontier/<int:pk>/', buy_tickers_from_effective_frontier_view,
         name='buy_tickers_effective_frontier'),

    path('update-ticker-action/<int:pk>/<slug:slug>/', update_ticker_api_view, name='update_ticker_api_view'),
    path('delete-ticker-from-portfolio/<int:pk>/', delete_ticker_from_portfolio_view,
         name='delete_ticker_from_portfolio'),

    path('update-ticker-from-portfolio/<int:pk>/', update_user_ticker_view, name='update_user_ticker'),

    path('refresh-ticker-data/<int:pk>/', refresh_ticker_data, name='refresh_ticker_data'),
    path('refresh-tickers-data/', refresh_tickers_data, name='refresh_tickers_data'),
    path('refresh-portfolio-tickers/<int:pk>/', refresh_portfolio_action_view, name='refresh_portfolio_tickers'),

    path('ajax/create-ticker-modal/<int:pk>/<int:dk>/', ajax_add_ticker_modal, name='ajax_add_ticker_modal'),
    path('ajax/portfolio/effective-frontier/<int:pk>/', ajax_portfolio_effective_frontier_view, name='ajax_effective_frontier'),
    path('ajax/show-graph/<int:pk>/', ajax_show_historic_graph, name='ajax_show_graph'),
    path('ajax/search-tickers/<int:pk>/', search_tickers, name='ajax-search_tickers'),
    path('create-random-portfolio-tickers/<int:pk>/', create_random_portfolios_view, name='create_random_port_tickers'),

    path('add-random-tickers-to-portfolio/<int:pk>/', add_random_tickers_to_portfolio, name='add_random_tickers_to_portfolio'),
    path('ajax-show-ticker-modal/<int:pk>/<int:dk>/', ajax_ticker_modal, name='ajax_show_ticker_modal'),
    path('ajax/update-ticker-data/<int:pk>/', ajax_refresh_portfolio_data, name='ajax_refresh_portfolio_ticker_data'),


  
    # strategies



]

frontend/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User


class BaseForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class LoginForm(BaseForm):
    username = forms.CharField(required=True, max_length=100)
    password = forms.CharField(required=True, widget=forms.PasswordInput)

frontend/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse


@api_view(['GET'])
def homepage_api_view(request, format=None):
    return Response({
        'tickers': reverse('api_tickers:home', request=request, format=format),
        'login':  reverse('token_obtain_pair', request=request, format=format),
        'refreshToken': reverse('token_refresh', request=request, format=format),
        
    }) 

frontend/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect, reverse, get_object_or_404
from django.views.generic import TemplateView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.db.models import Sum, F, Avg

import pandas as pd
import datetime
from dateutil import relativedelta


from tickers.models import Portfolio
from tickers.models import Ticker
from strategies.models import Strategy, StrategyTicker
from .forms import LoginForm
from tickers.form import PortFolioForm


@login_required
def homepage(request):
    context = dict()
    portfolios = Portfolio.objects.filter(user=request.user)
    context['portfolios'] = portfolios
    form = PortFolioForm(request.POST or None, initial={'user': request.user})
    if form.is_valid():
        form.save()
    context['form'] = form
    context['count_portfolios'] = portfolios.count()
    # total_earnings = portfolios.aggregate(total=Sum(F('current_value')-F('starting_investment'))) if portfolios.exists() else 0

    context['total_earnings'] =  total_earnings = 0
    context['average_earnings'] = 0 # total_earnings['total']/portfolios.count() if portfolios.exists() else 0
    context['starting_investment'] = portfolios.aggregate(Sum('starting_investment'))['starting_investment__sum'] if portfolios.exists() else 0
    context['average_expected_earnings'] = portfolios.aggregate(Avg('expected_portfolio_return'))['expected_portfolio_return__avg'] if portfolios.exists() else 0
    context['average_expected_variance'] =0 # portfolios.aggregate(Avg('expected_portfolio_variance'))[
         # 'expected_portfolio_variance__avg'] if portfolios.exists() else 0
    return render(request, 'dashboard.html', context)


def login_view(request):
    page_title = 'login'
    user = request.user
    url_change, btn_name = reverse('accounts:register'), 'Register'
    if user.is_authenticated:
        return HttpResponseRedirect('/')
    login_ = True
    form = LoginForm(request.POST or None)
    form_title, form_button = 'Συνδεση', 'Συνδεση'
    text = 'Εάν έχετε ήδη λογαριασμό, μπορείτε να συνδεθείτε'
    if form.is_valid():
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=raw_password)
        if user:
            login(request, user)
            return redirect('homepage')
        else:
            messages.warning(request, 'Ο κωδικός ή το email είναι λάθος.')
    return render(request, 'login.html', context=locals())


class StrategyView(TemplateView):
    template_name = 'strategy_homepage_view.html'


@login_required
def moving_average_trading_strategy_view(request):
    context = dict()
    context['object_list'] = Ticker.objects.all()[:50]
    strategy = Strategy.objects.get_or_create(user=request.user, category='a')
    context['strategy'] = strategy[0]
    strategy_tickers = StrategyTicker.objects.filter(strategy=strategy[0])
    context['strategy_tickers'] = strategy_tickers
    chart_data = pd.DataFrame()
    date = datetime.datetime.now() - relativedelta.relativedelta(month=3)

    data = dict()
    for ticker in strategy_tickers:
        MACD_line, signal_line, histogram = ticker.MACD()
        MACD_line = ['MACD', [MACD_line.columns.tolist() + MACD_line.reset_index().values.tolist()]]
        signal_line = ['Signal line', [signal_line.columns.tolist() + signal_line.reset_index().values.tolist()]]
        histogram = ['histogram', [histogram.columns.tolist() + histogram.reset_index().values.tolist()]]
        data[ticker.ticker.ticker] = [MACD_line, signal_line, histogram]
        # ticker.generate_signal(ticker.get_dataframe())
    context['data'] = data

    for ticker in strategy_tickers:
        ticker = ticker.ticker
        df = ticker.moving_average_trading_strategy(start_date=date)
        chart_data = df if chart_data.empty else chart_data.join(df, how='outer')
    chart_data.dropna(inplace=True)
    chart_headers = list(chart_data.columns.tolist())
    chart_data = [chart_data.columns.tolist()] + chart_data.reset_index().values.tolist()
    StrategyTicker.calculate_historic_rsi([ticker.ticker.ticker for ticker in strategy_tickers])
    context['chart_data'] = chart_data
    context['chart_headers'] = chart_headers
    context['portfolios'] = Portfolio.objects.filter(user=request.user)
    return render(request, 'tickers/moving_average_trading_view.html', context=context)


@login_required
def add_ticker_to_strategy_view(request, pk, dk):
    strategy = get_object_or_404(Strategy, id=pk)
    ticker = get_object_or_404(Ticker, id=dk)
    new_strategy_ticker = StrategyTicker.objects.create(
        strategy=strategy,
        ticker=ticker
    )
    messages.success(request, f'New ticker added - {new_strategy_ticker}')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def delete_ticker_from_strategy_view(request, pk):
    ticker = get_object_or_404(StrategyTicker, id=pk)
    ticker.delete()
    messages.warning(request, f'Ticker {ticker} removed from the strategy')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

frontend/templates/include/head.html
{% load static %}


<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
  <meta name="author" content="Creative Tim">
  <title>Argon Dashboard - Free Dashboard for Bootstrap 4</title>
  <!-- Favicon -->
  <link rel="icon" href="{% static '' %}assets/img/brand/favicon.png" type="image/png">
  <!-- Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
  <!-- Icons -->
  <link rel="stylesheet" href="{% static '' %}assets/vendor/nucleo/css/nucleo.css" type="text/css">
  <link rel="stylesheet" href="{% static '' %}assets/vendor/@fortawesome/fontawesome-free/css/all.min.css" type="text/css">
  <!-- Page plugins -->
  <!-- Argon CSS -->
  <link rel="stylesheet" href="{% static '' %}assets/css/argon.css?v=1.2.0" type="text/css">

    <link rel="stylesheet" href="{% static 'chart/Chart.bundle.min.js' %}" type="text/css">


</head>

frontend/templates/include/js.html
{% load static %}

<!-- Core -->
<script src="{% static '' %}assets/vendor/jquery/dist/jquery.min.js"></script>
<script src="{% static '' %}assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static '' %}assets/vendor/js-cookie/js.cookie.js"></script>
<script src="{% static '' %}assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
<script src="{% static '' %}assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js"></script>
  <!-- Optional JS -->
<script src="{% static '' %}assets/vendor/chart.js/dist/Chart.min.js"></script>
<script src="{% static '' %}assets/vendor/chart.js/dist/Chart.extension.js"></script>
  <!-- Argon JS -->
<script src="{% static '' %}assets/js/argon.js?v=1.2.0"></script>

frontend/templates/include/navbar.html
{% load static %}

 <nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">
      <!-- Brand -->
      <div class="sidenav-header  align-items-center">
        <a class="navbar-brand" href="javascript:void(0)">
          <img src="https://scontent.fath4-2.fna.fbcdn.net/v/t1.6435-9/158372396_10158488891454051_6117902423388182652_n.jpg?_nc_cat=103&ccb=1-3&_nc_sid=09cbfe&_nc_ohc=l5-NfrLjo54AX_PdtNo&_nc_ht=scontent.fath4-2.fna&oh=9da4b7896be713f08a217ea869fedbc0&oe=6096EE7A" class="navbar-brand-img" alt="...">
        </a>
      </div>
      <div class="navbar-inner">
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
          <!-- Nav items -->
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'homepage' %}">
                <i class="ni ni-tv-2 text-primary"></i>
                <span class="nav-link-text">Profile</span>
              </a>
            </li>
              <li class="nav-item">
              <a class="nav-link" href="{% url 'portfolio:portfolio_list_view' %}">
                <i class="ni ni-planet text-orange"></i>
                <span class="nav-link-text">Portfolios</span>
              </a>
            </li>
              <li class="nav-item">
              <a class="nav-link" href="{% url 'portfolio:ticker_list_view' %}">
                <i class="ni ni-planet text-orange"></i>
                <span class="nav-link-text">Tickers</span>
              </a>
              </li>
              <li class="nav-item">
              <a class="nav-link" href="{% url 'strategy_homepage' %}">
                <i class="ni ni-planet text-orange"></i>
                <span class="nav-link-text">Strategies</span>
              </a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'setting:homepage' %}">
                      <i class="ni ni-planet text-orange"></i>
                      <span class="nav-link-text">Settings</span>
                  </a>
              </li>

          </ul>

        </div>
      </div>
    </div>
  </nav>